### ISSUE TITLE
Licensing Info?

### ISSUE THREAD

**Issue by sdellis** [IIIF/iiif-osd-viewer#4]
I have developed a basic [IIIF Image Field](https://github.com/pulibrary/iiif_image_field) Drupal module that allows the inclusion of IIIF images in Drupal.  I am using your jQuery Plugin (nice work!) for the front-end display when the "Zoom" option is set to true.  Before I can release it to the public, I want to make sure that I can redistribute your plugin with it.  

Do you plan to include a license with this library?  Thanks in advance for any info!

**Comment by jchristo4** [comment]
@sdellis Just added a license to this repo. Will add documentation on usage with examples soon

**Comment by sdellis** [comment]
Great!  Thank you.  FYI - I added "rotation options" to your plugin in the module, and have made it clear in the source.  It was not much, but I'd be happy to create a pull request if you want to include it.

Also, it turns out that Drupal modules need to be under GPLv3 to be hosted at Drupal.org.  That's the plan as it allows for wider visibility and ease of use.  GPLv3 allows for redistribution of code under the Apache 2.0 license, so I think we're good.
